# Generated by Django 4.2.11 on 2024-08-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestcasoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='member',
            new_name='members',
        ),
    ]
