# Generated by Django 4.2.11 on 2024-08-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestcasoapp', '0002_rename_member_area_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
