# Generated by Django 4.2.11 on 2024-08-13 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestcasoapp', '0003_complaint_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='file_add',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='file_add',
        ),
        migrations.RemoveField(
            model_name='proceedingcomplaint',
            name='file_add',
        ),
    ]
