# Generated by Django 4.2.11 on 2024-08-13 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestcasoapp', '0004_remove_answer_file_add_remove_complaint_file_add_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProceedingComplaintAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_add', models.FileField(upload_to='media/')),
                ('proceedingcomplaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='gestcasoapp.proceedingcomplaint')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_add', models.FileField(upload_to='media/')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='gestcasoapp.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_add', models.FileField(upload_to='media/')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='gestcasoapp.answer')),
            ],
        ),
    ]
