# Generated by Django 4.2.11 on 2024-08-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestcasoapp', '0005_proceedingcomplaintattachment_complaintattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
